name: precription
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-24.0.dev

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.6
  image_picker: ^1.1.2
  flutter_tesseract_ocr: ^0.4.28
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  firebase_core: ^3.12.0
  image: ^4.5.3
  camerawesome: ^2.1.0
  exif: ^3.3.0
  cloud_firestore: ^5.6.4
  http: ^1.3.0
  flutter_media_store: ^1.3.1
  google_fonts: ^6.2.1
  animations: ^2.0.11
  dio: ^5.8.0+1
  firebase_auth: ^5.5.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
